"""
Q8.
You have a shopping list containing several item names.

Use a loop to display each item with a number before it.

For example, the output should conceptually look like:

1. Apples
2. Milk
3. Bread

The number should be generated by your program rather than manually written.
"""

shopping_list = ['Apples', 'Milk', 'Bread']


for index in range(0, len(shopping_list)):
    print(f'{index + 1}. {shopping_list[index]}')